version: 2.1
jobs:
  lint212_jdk8:
    docker:
      - image: hseeberger/scala-sbt:8u181_2.12.8_1.2.8
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.8! check
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  lint212_jdk11:
    docker:
      - image: hseeberger/scala-sbt:11.0.2_2.12.8_1.2.8
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.8! check
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test212_jdk8:
    docker:
      - image: hseeberger/scala-sbt:8u181_2.12.8_1.2.8
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.8! test:run
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test212_jdk11:
    docker:
      - image: hseeberger/scala-sbt:11.0.2_2.12.8_1.2.8
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.8! test:run
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  release:
    docker:
      - image: hseeberger/scala-sbt:8u181_2.12.8_1.2.8
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: sbt-cache
      - run: echo -n "${PGP_PUBLIC}" | base64 -d > /tmp/public.asc
      - run: echo -n "${PGP_SECRET}" | base64 -d > /tmp/secret.asc
      - run: sbt releaseEarly
  microsite:
    docker:
      - image: hseeberger/scala-sbt:8u181_2.12.8_1.2.8
    steps:
      - add_ssh_keys:
          fingerprints:
            - "11:2c:fa:98:69:d8:a1:d5:76:2e:38:d0:91:39:85:ce"
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.8! doc
      - run: sbt ++2.12.8! microsite/makeMicrosite
      - run: sbt ++2.12.8! microsite/publishMicrosite
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

workflows:
  version: 2
  build:
    jobs:
      - lint212_jdk8
      - lint212_jdk11
      - test212_jdk8:
          requires:
            - lint212_jdk8
      - test212_jdk11:
          requires:
            - lint212_jdk11
      - release:
          context: Sonatype
          requires:
            - test212_jdk8
            - test212_jdk11
          filters:
            branches:
              only: master
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - microsite:
          requires:
            - release
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/

